name: CI/CD Pipeline

# Define os eventos que disparam a execução do pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define as etapas do pipeline
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: echo "Building the application..."

  dev:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
    - name: Deploy
      run: echo "Deploying to the Dev environment..."

  hml:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: HML
    steps:
    - name: Deploy
      run: echo "Deploying to the HML environment..."

  prd:
    needs: [dev, hml]
    runs-on: ubuntu-latest
    environment:
      name: PRD
    steps:
    - name: Deploy
      run: echo "Deploying to the PRD environment..."
