name: CI/CD Pipeline

# Define os eventos que disparam a execução do pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define as etapas do pipeline
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: echo "Building the application..."
      
    - name: Sonar
      run: |
        echo "Analisando the application..."
        sleep 20
        echo "Analisando the application..."
        echo "Analisando the application..."
        echo "Analisando the application..."
        echo "Analisando the application..."
        echo "Analisando the application..."
        echo "Analisando the application..."
        sleep 10

  dev:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
    - name: Deploy
      run: echo "Deploying to the Dev environment..."

  hml:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: HML
    steps:
    - name: Deploy
      run: echo "Deploying to the HML environment..."
      
    - name: Teste de Carga
      run: |
        echo "Realizando teste de Carga..."
        sleep 20
        echo "10 the hits..."
        echo "20 the hits..."
        echo "30 the hits..."
        echo "40 the hits..."
        echo "50 the hits..."
        echo "60 the hits..."
        sleep 10
        echo "70 the hits..."
        echo "10 the hits..."
        echo "10 the hits..."
        sleep 10
        echo "10 the hits..."
        echo "10 the hits..."
        echo "10 the hits..."
        sleep 30

  prd:
    needs: [dev, hml]
    runs-on: ubuntu-latest
    environment:
      name: PRD
    steps:
    - name: Login Cluster
      run: |
        echo "Deploying to the PRD environment..."
        sleep 10
      
    - name: Docker Login Variaveis
      run: |
        echo "Atualizando to the PRD environment..."
        sleep 20
        
    - name: Helm Install
      run: |
        echo "Deploying to the PRD environment..."
        sleep 30
        
    - name: Helm Upgrade
      run: |
        echo "Deploying to the PRD environment..."
        sleep 60
